### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wmww** [eyelash/tutorials#3]
I noticed that you haven't put your code in this repo under an open source license. If you want others to be able to use and build on what you've written, please consider adding a license so there is no fear of future difficulties. The MIT license would be preferable to me as it is the standard for many Wayland related projects. Thanks.

**Comment by eyelash** [comment]
I'll have to look into that but I don't think the MIT license is what I want here. Anyway, feel free to use the code in this repository in whatever way you like.
